package api

//ErrorString has a string
type ErrorString struct {
	Str string
}

func (e *ErrorString) Error() string {
	return e.Str
}

// Generated by https://quicktype.io

type ErrorJSON struct {
	Error   Error `json:"Error"`
	Success bool  `json:"success"`
}

type Error struct {
	Message string `json:"Message"`
}
